[project]
name = "consist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zneedell", email = "zneedell@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "black>=25.11.0",
    "dlt>=1.18.2",
    "duckdb>=1.4.2",
    "duckdb-engine>=0.17.0",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "pydantic>=2.12.4",
    "sqlalchemy>=2.0.44",
    "sqlmodel>=0.0.27",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "alembic>=1.17.2",
    "pytest>=9.0.1",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.6",
]
